alias: Kitchen - Lights on
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: group.motion_kitchen
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: template
      value_template: "{{ not is_state('alarm_control_panel.ring_alarm', 'armed_away') }}"
    - condition: template
      value_template: "{{ (trigger.entity_id == 'group.motion_kitchen') and is_state('light.kitchen_group', 'off') }}"
    - condition: time
      after: '07:00:00'
      before: '23:00:00'
action:
  - service: 'light.turn_on'
    data_template:
      entity_id: >-
        {% if (now().hour < 10) %} light.kitchen_group_dimmable
        {% else %} light.kitchen_group
        {% endif%}
      brightness_pct: >-
        {% if (now().hour < 10) %} 20
        {% elif (now().hour < 21) %} 100
        {% elif (now().hour < 23) or ((now().hour == 23) and (now().minute < 45)) %} 20
        {% else %} 0
        {% endif%}