path: house.admin
title: Administration
icon: mdi:home-assistant
panel: false

badges:
  !include ../includes/_badges.yaml

cards:
  # Col 1
  - type: vertical-stack
    cards:
      - !include ../includes/footer_card.yaml
      # Battery almost done
      - !include ../includes/low_battery_devices.yaml
      # Things with issues
      - !include ../includes/broken_entities.yaml
      # UPS
      - !include ../includes/admin/admin_monitoring_ups.yaml
      # Pi-hole
      - !include ../includes/admin/admin_monitoring_pi_hole.yaml
      - !include ../includes/bottom-card.yaml
  # Col 2
  - type: vertical-stack
    cards:
      # Speed test
      - !include ../includes/admin/admin_monitoring_speed_test.yaml
      # NUC
      - !include ../includes/admin/admin_monitoring_nuc.yaml
      - !include ../includes/bottom-card.yaml
  # Col 3
  - type: vertical-stack
    cards:
      # VM
      - !include ../includes/admin/admin_monitoring_vm.yaml
      # Synology
      - !include ../includes/admin/admin_monitoring_synology.yaml
      # Automations
      - type: custom:decluttering-card
        template: automation
        variables:
          - entity1: 'system*'
          - entity2: 'entities*'
          - entity3: 'information*'
      - !include ../includes/bottom-card.yaml