alias: House - Set the variable sleep mode
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: alarm_control_panel.ring_alarm
    to: 'armed_home'
  - platform: state
    entity_id: alarm_control_panel.ring_alarm
    to: 'disarmed'
  - platform: homeassistant
    event: start
action:
  - service_template: >
      {% if (trigger.to_state is defined) and (trigger.to_state.state == 'armed_home') %}
        input_boolean.turn_on
      {% else %}
        input_boolean.turn_off
      {% endif %}
    entity_id: 'input_boolean.sleep_mode'