# Synology
platform: synologydsm
host: !secret entitie_synology_host
username: !secret entitie_synology_username
password: !secret entitie_synology_password
monitored_conditions:
  - cpu_total_load
  - memory_real_usage
  - network_up
  - volume_status
  - volume_percentage_used
  - volume_size_total
  - volume_size_used
  - disk_smart_status