alias: Bedroom - Alarm armed away
trigger:
  - platform: state
    entity_id: alarm_control_panel.ring_alarm
    to: 'armed_away'
action:
  - service: light.turn_off
    entity_id: light.bedroom_group
  - service: media_player.media_pause
    data:
      entity_id:
        - media_player.bedroom # Sonos
  - service: media_player.turn_off # Nvidia shield
    data:
      entity_id: media_player.nvidia_shield